name = "multivarBernoulli"
uuid = "2b8086c1-fe4f-4323-9725-553dafa0e9d7"
authors = ["Charles Dufour"]
version = "1.0.0-DEV"

[compat]
Aqua = "0.8"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
